### ISSUE TITLE
Applicaiton issue under Wayland

### ISSUE THREAD

**Issue by foldynl** [flathub/io.github.foldynl.QLog#3]
@AsciiWolf 

It seems to be an issue under wayland due to an [issue](https://bugreports.qt.io/browse/QTBUG-87332) in QT 5.15 which is used for QLog flatpak.

**in short issue description:** detached windows won't be attach if the flatpak is running under wayland (foldynl/Qlog#266).

I have tested that everything is working if I run the flatpak:
`flatpak run --socket=x11 --nosocket=wayland --socket=fallback-x11 io.github.foldynl.QLog`

I am not Flatpak expert therefore I don't provide you fix but I can see two options how to fix it

1) to modify the yaml file to not use wayland
2) (not tested option) - to modify yaml to use QT6.6- and we have to hope that it will be fixed. QLog source code has been tested against QT6.6

For me, option 1 is preferred.

**Comment by AsciiWolf** [comment]
Thanks for reporting this! I can confirm the issue and have pushed a PR to remove the wayland socket until this gets fixed.
